-- MySQL Script generated by MySQL Workbench
-- Mon May 24 18:02:08 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Lokalizacja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lokalizacja` (
  `ID` INT NOT NULL,
  `Województwo` VARCHAR(50) NOT NULL,
  `Miasto` VARCHAR(50) NOT NULL,
  `KodPocztowy` CHAR(6) NOT NULL,
  `Miejscowość` VARCHAR(50) NULL,
  `Ulica` VARCHAR(50) NULL,
  `NumerMieszkania` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DaneOsobowe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DaneOsobowe` (
  `ID` INT NOT NULL,
  `Imię` VARCHAR(50) NOT NULL,
  `Nazwisko` VARCHAR(50) NOT NULL,
  `Pesel` CHAR(11) NOT NULL,
  `E-mail` VARCHAR(50) NOT NULL,
  `NumerTelefonu` CHAR(9) NOT NULL,
  `Lokalizacja_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Lokalizacja_ID`),
  INDEX `fk_DaneOsobowe_Lokalizacja1_idx` (`Lokalizacja_ID` ASC) VISIBLE,
  CONSTRAINT `fk_DaneOsobowe_Lokalizacja1`
    FOREIGN KEY (`Lokalizacja_ID`)
    REFERENCES `mydb`.`Lokalizacja` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`KontoKlient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`KontoKlient` (
  `ID` INT NOT NULL,
  `Login` VARCHAR(50) NULL,
  `Hasło` VARCHAR(64) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Majątek`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Majątek` (
  `ID` INT NOT NULL,
  `Nieruchomości` FLOAT NULL,
  `Pensja` FLOAT NULL,
  `Inne` FLOAT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Klient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Klient` (
  `ID` INT NOT NULL,
  `DaneOsobowe_ID` INT NOT NULL,
  `KontoKlient_ID` INT NOT NULL,
  `Majątek_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `DaneOsobowe_ID`, `KontoKlient_ID`, `Majątek_ID`),
  INDEX `fk_Klient_DaneOsobowe_idx` (`DaneOsobowe_ID` ASC) VISIBLE,
  INDEX `fk_Klient_KontoKlient1_idx` (`KontoKlient_ID` ASC) VISIBLE,
  INDEX `fk_Klient_Majątek1_idx` (`Majątek_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Klient_DaneOsobowe`
    FOREIGN KEY (`DaneOsobowe_ID`)
    REFERENCES `mydb`.`DaneOsobowe` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Klient_KontoKlient1`
    FOREIGN KEY (`KontoKlient_ID`)
    REFERENCES `mydb`.`KontoKlient` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Klient_Majątek1`
    FOREIGN KEY (`Majątek_ID`)
    REFERENCES `mydb`.`Majątek` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Data` (
  `ID` INT NOT NULL,
  `Rok` YEAR NOT NULL,
  `Miesiąc` VARCHAR(50) NOT NULL,
  `Dzień` INT NOT NULL,
  `Czas` TIME NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RodzajTransakcji`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RodzajTransakcji` (
  `ID` INT NOT NULL,
  `Nazwa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Transakcje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Transakcje` (
  `ID` INT NOT NULL,
  `Wartość` FLOAT NOT NULL,
  `Klient_ID` INT NOT NULL,
  `Data_ID` INT NOT NULL,
  `RodzajTransakcji_ID` INT NOT NULL,
  `Lokalizacja_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Klient_ID`, `Data_ID`, `RodzajTransakcji_ID`, `Lokalizacja_ID`),
  INDEX `fk_Transakcje_Klient1_idx` (`Klient_ID` ASC) VISIBLE,
  INDEX `fk_Transakcje_Data1_idx` (`Data_ID` ASC) VISIBLE,
  INDEX `fk_Transakcje_RodzajTransakcji1_idx` (`RodzajTransakcji_ID` ASC) VISIBLE,
  INDEX `fk_Transakcje_Lokalizacja1_idx` (`Lokalizacja_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Transakcje_Klient1`
    FOREIGN KEY (`Klient_ID`)
    REFERENCES `mydb`.`Klient` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transakcje_Data1`
    FOREIGN KEY (`Data_ID`)
    REFERENCES `mydb`.`Data` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transakcje_RodzajTransakcji1`
    FOREIGN KEY (`RodzajTransakcji_ID`)
    REFERENCES `mydb`.`RodzajTransakcji` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transakcje_Lokalizacja1`
    FOREIGN KEY (`Lokalizacja_ID`)
    REFERENCES `mydb`.`Lokalizacja` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RachunekKredytowy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RachunekKredytowy` (
  `ID` CHAR(16) NOT NULL,
  `Klient_ID` INT NOT NULL,
  `PIN` CHAR(4) NULL,
  `Środki` FLOAT NULL,
  PRIMARY KEY (`ID`, `Klient_ID`),
  INDEX `fk_RachunkeKredytowy_Klient1_idx` (`Klient_ID` ASC) VISIBLE,
  CONSTRAINT `fk_RachunkeKredytowy_Klient1`
    FOREIGN KEY (`Klient_ID`)
    REFERENCES `mydb`.`Klient` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RachunekDebetowy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RachunekDebetowy` (
  `ID` CHAR(16) NOT NULL,
  `Klient_ID` INT NOT NULL,
  `PIN` CHAR(4) NOT NULL,
  `Debet` FLOAT NOT NULL,
  PRIMARY KEY (`ID`, `Klient_ID`),
  INDEX `fk_RachunekDebetowy_Klient1_idx` (`Klient_ID` ASC) VISIBLE,
  CONSTRAINT `fk_RachunekDebetowy_Klient1`
    FOREIGN KEY (`Klient_ID`)
    REFERENCES `mydb`.`Klient` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RodzajLokaty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RodzajLokaty` (
  `ID` INT NOT NULL,
  `Nazwa` VARCHAR(50) NOT NULL,
  `Oprocentowanie` FLOAT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lokata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lokata` (
  `ID` INT NOT NULL,
  `Klient_ID` INT NOT NULL,
  `Depozyt` FLOAT NULL,
  `DataZałożenia_ID` INT NOT NULL,
  `DataZakończenia_ID` INT NOT NULL,
  `RodzajLokaty_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Klient_ID`, `DataZałożenia_ID`, `DataZakończenia_ID`, `RodzajLokaty_ID`),
  INDEX `fk_Lokata_Klient1_idx` (`Klient_ID` ASC) VISIBLE,
  INDEX `fk_Lokata_Data1_idx` (`DataZałożenia_ID` ASC) VISIBLE,
  INDEX `fk_Lokata_Data2_idx` (`DataZakończenia_ID` ASC) VISIBLE,
  INDEX `fk_Lokata_RodzajLokaty1_idx` (`RodzajLokaty_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Lokata_Klient1`
    FOREIGN KEY (`Klient_ID`)
    REFERENCES `mydb`.`Klient` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lokata_Data1`
    FOREIGN KEY (`DataZałożenia_ID`)
    REFERENCES `mydb`.`Data` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lokata_Data2`
    FOREIGN KEY (`DataZakończenia_ID`)
    REFERENCES `mydb`.`Data` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lokata_RodzajLokaty1`
    FOREIGN KEY (`RodzajLokaty_ID`)
    REFERENCES `mydb`.`RodzajLokaty` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rodzaj Kredytu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rodzaj Kredytu` (
  `ID` INT NOT NULL,
  `Nazwa` VARCHAR(50) NULL,
  `Oprocentowanie` FLOAT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Kredyt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Kredyt` (
  `ID` INT NOT NULL,
  `Wartość` FLOAT NOT NULL,
  `Klient_ID` INT NOT NULL,
  `DataZałożenia_ID` INT NOT NULL,
  `DataZakończenia_ID` INT NOT NULL,
  `Rodzaj Kredytu_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Klient_ID`, `DataZałożenia_ID`, `DataZakończenia_ID`, `Rodzaj Kredytu_ID`),
  INDEX `fk_Kredyt_Klient1_idx` (`Klient_ID` ASC) VISIBLE,
  INDEX `fk_Kredyt_Data1_idx` (`DataZałożenia_ID` ASC) VISIBLE,
  INDEX `fk_Kredyt_Data2_idx` (`DataZakończenia_ID` ASC) VISIBLE,
  INDEX `fk_Kredyt_Rodzaj Kredytu1_idx` (`Rodzaj Kredytu_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Kredyt_Klient1`
    FOREIGN KEY (`Klient_ID`)
    REFERENCES `mydb`.`Klient` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Kredyt_Data1`
    FOREIGN KEY (`DataZałożenia_ID`)
    REFERENCES `mydb`.`Data` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Kredyt_Data2`
    FOREIGN KEY (`DataZakończenia_ID`)
    REFERENCES `mydb`.`Data` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Kredyt_Rodzaj Kredytu1`
    FOREIGN KEY (`Rodzaj Kredytu_ID`)
    REFERENCES `mydb`.`Rodzaj Kredytu` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Stanowisko`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Stanowisko` (
  `ID` INT NOT NULL,
  `Nazwa` VARCHAR(50) NOT NULL,
  `Płaca podstawowa` FLOAT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`KontoPracownik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`KontoPracownik` (
  `ID` INT NOT NULL,
  `Login` VARCHAR(45) NULL,
  `Hasło` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pracownik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pracownik` (
  `ID` INT NOT NULL,
  `DaneOsobowe_ID` INT NOT NULL,
  `Stanowisko_ID` INT NOT NULL,
  `KontoPracownik_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `DaneOsobowe_ID`, `Stanowisko_ID`, `KontoPracownik_ID`),
  INDEX `fk_Pracownik_DaneOsobowe1_idx` (`DaneOsobowe_ID` ASC) VISIBLE,
  INDEX `fk_Pracownik_Stanowisko1_idx` (`Stanowisko_ID` ASC) VISIBLE,
  INDEX `fk_Pracownik_KontoPracownik1_idx` (`KontoPracownik_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Pracownik_DaneOsobowe1`
    FOREIGN KEY (`DaneOsobowe_ID`)
    REFERENCES `mydb`.`DaneOsobowe` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pracownik_Stanowisko1`
    FOREIGN KEY (`Stanowisko_ID`)
    REFERENCES `mydb`.`Stanowisko` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pracownik_KontoPracownik1`
    FOREIGN KEY (`KontoPracownik_ID`)
    REFERENCES `mydb`.`KontoPracownik` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Wypłata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Wypłata` (
  `ID` INT NOT NULL,
  `Miesiąc` VARCHAR(50) NOT NULL,
  `Pensja Całkowita` VARCHAR(50) NOT NULL,
  `Pracownik_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Pracownik_ID`),
  INDEX `fk_Wypłata_Pracownik1_idx` (`Pracownik_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Wypłata_Pracownik1`
    FOREIGN KEY (`Pracownik_ID`)
    REFERENCES `mydb`.`Pracownik` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Premia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Premia` (
  `ID` INT NOT NULL,
  `Nazwa` VARCHAR(50) NULL,
  `Wartość` FLOAT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Premia_has_Wypłata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Premia_has_Wypłata` (
  `Premia_ID` INT NOT NULL,
  `Wypłata_ID` INT NOT NULL,
  PRIMARY KEY (`Premia_ID`, `Wypłata_ID`),
  INDEX `fk_Premia_has_Wypłata_Wypłata1_idx` (`Wypłata_ID` ASC) VISIBLE,
  INDEX `fk_Premia_has_Wypłata_Premia1_idx` (`Premia_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Premia_has_Wypłata_Premia1`
    FOREIGN KEY (`Premia_ID`)
    REFERENCES `mydb`.`Premia` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Premia_has_Wypłata_Wypłata1`
    FOREIGN KEY (`Wypłata_ID`)
    REFERENCES `mydb`.`Wypłata` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
